#https://runnable.com/docker/python/dockerize-your-python-application
FROM python:3
WORKDIR ../../python
#ADD ask_API.py /
#tells Docker which additional commands to execute
#RUN pip install requests json
#tells Docker to execute the command when the image loads
#CMD [ "python", "./ask_API.py" ]


ADD my_script.py /

RUN pip install pystrich

CMD [ "python", "./my_script.py" ]