#https://runnable.com/docker/python/dockerize-your-python-application
FROM python:3
WORKDIR ../../python
#ADD ask_API.py /
#tells Docker which additional commands to execute
#RUN pip install pystrich
#tells Docker to execute the command when the image loads
CMD [ "python", "./ask_API.py]